In [ ]:
! pip install pandas

In [1]:

import pandas as pd

In [2]:
postings = pd.read_csv('postings.csv')

In [6]:
pd.set_option('display.max_columns', None)
postings.head()

,job_id,company_name,title,description,max_salary,pay_period,location,company_id,views,med_salary,min_salary,formatted_work_type,applies,original_listed_time,remote_allowed,job_posting_url,application_url,application_type,expiry,closed_time,formatted_experience_level,skills_desc,listed_time,posting_domain,sponsored,work_type,currency,compensation_type,normalized_salary,zip_code,fips
0,921716,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,20.0,HOURLY,"Princeton, NJ",2774458.0,20.0,NaN,17.0,Full-time,2.0,1.713398e+12,NaN,https://www.linkedin.com/jobs/view/921716/?trk...,NaN,ComplexOnsiteApply,1.715990e+12,NaN,NaN,Requirements: \n\nWe are seeking a College or ...,1.713398e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,38480.0,8540.0,34021.0
1,1829192,NaN,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committ...",50.0,HOURLY,"Fort Collins, CO",NaN,1.0,NaN,30.0,Full-time,NaN,1.712858e+12,NaN,https://www.linkedin.com/jobs/view/1829192/?tr...,NaN,ComplexOnsiteApply,1.715450e+12,NaN,NaN,NaN,1.712858e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,83200.0,80521.0,8069.0
2,10998357,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,65000.0,YEARLY,"Cincinnati, OH",64896719.0,8.0,NaN,45000.0,Full-time,NaN,1.713278e+12,NaN,https://www.linkedin.com/jobs/view/10998357/?t...,NaN,ComplexOnsiteApply,1.715870e+12,NaN,NaN,We are currently accepting resumes for FOH - A...,1.713278e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,55000.0,45202.0,39061.0
3,23221523,"Abrams Fensterman, LLP",Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,175000.0,YEARLY,"New Hyde Park, NY",766262.0,16.0,NaN,140000.0,Full-time,NaN,1.712896e+12,NaN,https://www.linkedin.com/jobs/view/23221523/?t...,NaN,ComplexOnsiteApply,1.715488e+12,NaN,NaN,This position requires a baseline understandin...,1.712896e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,11040.0,36059.0
4,35982263,NaN,Service Technician,Looking for HVAC service tech with experience ...,80000.0,YEARLY,"Burlington, IA",NaN,3.0,NaN,60000.0,Full-time,NaN,1.713452e+12,NaN,https://www.linkedin.com/jobs/view/35982263/?t...,NaN,ComplexOnsiteApply,1.716044e+12,NaN,NaN,NaN,1.713452e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,70000.0,52601.0,19057.0

In [7]:
postings.shape

(123849, 31)

In [9]:
postings.columns

Index(['job_id', 'company_name', 'title', 'description', 'max_salary',
       'pay_period', 'location', 'company_id', 'views', 'med_salary',
       'min_salary', 'formatted_work_type', 'applies', 'original_listed_time',
       'remote_allowed', 'job_posting_url', 'application_url',
       'application_type', 'expiry', 'closed_time',
       'formatted_experience_level', 'skills_desc', 'listed_time',
       'posting_domain', 'sponsored', 'work_type', 'currency',
       'compensation_type', 'normalized_salary', 'zip_code', 'fips'],
      dtype='object')

In [9]:
postings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 123849 entries, 0 to 123848
Data columns (total 31 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   job_id                      123849 non-null  int64
 1   company_name                122130 non-null  object
 2   title                       123849 non-null  object
 3   description                 123842 non-null  object
 4   max_salary                  29793 non-null   float64
 5   pay_period                  36073 non-null   object
 6   location                    123849 non-null  object
 7   company_id                  122132 non-null  float64
 8   views                       122160 non-null  float64
 9   med_salary                  6280 non-null    float64
 10  min_salary                  29793 non-null   float64
 11  formatted_work_type         123849 non-null  object
 12  applies                     23320 non-null   float64
 13  original_listed_time        123849 non-null  float64
 14  remote_allowed              15246 non-null   float64
 15  job_posting_url             123849 non-null  object
 16  application_url             87184 non-null   object
 17  application_type            123849 non-null  object
 18  expiry                      123849 non-null  float64
 19  closed_time                 1073 non-null    float64
 20  formatted_experience_level  94440 non-null   object
 21  skills_desc                 2439 non-null    object
 22  listed_time                 123849 non-null  float64
 23  posting_domain              83881 non-null   object
 24  sponsored                   123849 non-null  int64
 25  work_type                   123849 non-null  object
 26  currency                    36073 non-null   object
 27  compensation_type           36073 non-null   object
 28  normalized_salary           36073 non-null   float64
 29  zip_code                    102977 non-null  float64
 30  fips                        96434 non-null   float64
dtypes: float64(14), int64(2), object(15)
memory usage: 29.3+ MB

In [10]:
postings.dtypes

job_id                          int64
company_name                   object
title                          object
description                    object
max_salary                    float64
pay_period                     object
location                       object
company_id                    float64
views                         float64
med_salary                    float64
min_salary                    float64
formatted_work_type            object
applies                       float64
original_listed_time          float64
remote_allowed                float64
job_posting_url                object
application_url                object
application_type               object
expiry                        float64
closed_time                   float64
formatted_experience_level     object
skills_desc                    object
listed_time                   float64
posting_domain                 object
sponsored                       int64
work_type                      object
currency                       object
compensation_type              object
normalized_salary             float64
zip_code                      float64
fips                          float64
dtype: object

In [12]:
postings.describe()

,job_id,max_salary,company_id,views,med_salary,min_salary,applies,original_listed_time,remote_allowed,expiry,closed_time,listed_time,sponsored,normalized_salary,zip_code,fips
count,1.238490e+05,2.979300e+04,1.221320e+05,122160.000000,6280.000000,2.979300e+04,23320.000000,1.238490e+05,15246.0,1.238490e+05,1.073000e+03,1.238490e+05,123849.0,3.607300e+04,102977.000000,96434.000000
mean,3.896402e+09,9.193942e+04,1.220401e+07,14.618247,22015.619876,6.491085e+04,10.591981,1.713152e+12,1.0,1.716213e+12,1.712928e+12,1.713204e+12,0.0,2.053270e+05,50400.491887,28713.879887
std,8.404355e+07,7.011101e+05,2.554143e+07,85.903598,52255.873846,4.959738e+05,29.047395,4.848209e+08,0.0,2.321394e+09,3.622893e+08,3.989122e+08,0.0,5.097627e+06,30252.232515,16015.929825
min,9.217160e+05,1.000000e+00,1.009000e+03,1.000000,0.000000,1.000000e+00,1.000000,1.701811e+12,1.0,1.712903e+12,1.712346e+12,1.711317e+12,0.0,0.000000e+00,1001.000000,1003.000000
25%,3.894587e+09,4.828000e+01,1.435200e+04,3.000000,18.940000,3.700000e+01,1.000000,1.712863e+12,1.0,1.715481e+12,1.712670e+12,1.712886e+12,0.0,5.200000e+04,24112.000000,13121.000000
50%,3.901998e+09,8.000000e+04,2.269650e+05,4.000000,25.500000,6.000000e+04,3.000000,1.713395e+12,1.0,1.716042e+12,1.712670e+12,1.713408e+12,0.0,8.150000e+04,48059.000000,29183.000000
75%,3.904707e+09,1.400000e+05,8.047188e+06,8.000000,2510.500000,1.000000e+05,8.000000,1.713478e+12,1.0,1.716088e+12,1.713283e+12,1.713484e+12,0.0,1.250000e+05,78201.000000,42077.000000
max,3.906267e+09,1.200000e+08,1.034730e+08,9975.000000,750000.000000,8.500000e+07,967.000000,1.713573e+12,1.0,1.729125e+12,1.713562e+12,1.713573e+12,0.0,5.356000e+08,99901.000000,56045.000000

In [13]:
postings['title']

0                                     Marketing Coordinator
1                         Mental Health Therapist/Counselor
2                               Assitant Restaurant Manager
3         Senior Elder Law / Trusts and Estates Associat...
4                                        Service Technician
                                ...
123844                     Title IX/Investigations Attorney
123845         Staff Software Engineer, ML Serving Platform
123846                 Account Executive, Oregon/Washington
123847                         Business Development Manager
123848                    Marketing Social Media Specialist
Name: title, Length: 123849, dtype: object

In [16]:
postings_filter=postings[['job_id', 'title', 'description']]
postings_filter

,job_id,title,description
0,921716,Marketing Coordinator,Job descriptionA leading real estate firm in N...
1,1829192,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committ..."
2,10998357,Assitant Restaurant Manager,The National Exemplar is accepting application...
3,23221523,Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...
4,35982263,Service Technician,Looking for HVAC service tech with experience ...
...,...,...,...
123844,3906267117,Title IX/Investigations Attorney,Our Walnut Creek office is currently seeking a...
123845,3906267126,"Staff Software Engineer, ML Serving Platform",About Pinterest:\n\nMillions of people across ...
123846,3906267131,"Account Executive, Oregon/Washington",Company Overview\n\nEPS Learning is a leading ...
123847,3906267195,Business Development Manager,The Business Development Manager is a 'hunter'...
123848,3906267224,Marketing Social Media Specialist,Marketing Social Media Specialist - $70k – $75...

In [17]:
postings['title'].unique()

array(['Marketing Coordinator', 'Mental Health Therapist/Counselor',
       'Assitant Restaurant Manager', ...,
       'Staff Software Engineer, ML Serving Platform',
       'Account Executive, Oregon/Washington',
       'Marketing Social Media Specialist'], dtype=object)

In [18]:
postings['title'].value_counts()

title
Sales Manager                                       673
Customer Service Representative                     373
Project Manager                                     354
Administrative Assistant                            254
Senior Accountant                                   238
                                                   ...
Cath Lab / IR Technologist (Cert) - Cardiac Cath      1
Energy Administrative Assistant Part Time             1
ASSOCIATE CLIENT SUCCESS MANAGER                      1
Student Nurse - Telemetry                             1
Marketing Social Media Specialist                     1
Name: count, Length: 72521, dtype: int64

In [21]:
print=(postings['max_salary'].max())
print

120000000.0

In [3]:
posting_cleaned = postings.copy()
posting_cleaned.head()

,job_id,company_name,title,description,max_salary,pay_period,location,company_id,views,med_salary,...,skills_desc,listed_time,posting_domain,sponsored,work_type,currency,compensation_type,normalized_salary,zip_code,fips
0,921716,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,20.0,HOURLY,"Princeton, NJ",2774458.0,20.0,NaN,...,Requirements: \n\nWe are seeking a College or ...,1.713398e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,38480.0,8540.0,34021.0
1,1829192,NaN,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committ...",50.0,HOURLY,"Fort Collins, CO",NaN,1.0,NaN,...,NaN,1.712858e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,83200.0,80521.0,8069.0
2,10998357,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,65000.0,YEARLY,"Cincinnati, OH",64896719.0,8.0,NaN,...,We are currently accepting resumes for FOH - A...,1.713278e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,55000.0,45202.0,39061.0
3,23221523,"Abrams Fensterman, LLP",Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,175000.0,YEARLY,"New Hyde Park, NY",766262.0,16.0,NaN,...,This position requires a baseline understandin...,1.712896e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,11040.0,36059.0
4,35982263,NaN,Service Technician,Looking for HVAC service tech with experience ...,80000.0,YEARLY,"Burlington, IA",NaN,3.0,NaN,...,NaN,1.713452e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,70000.0,52601.0,19057.0

In [4]:
posting_cleaned.rename({'title': 'job_title', 'description': 'job_description', 'applies': 'num_applicants'}, axis=1, inplace=True)

In [18]:
posting_cleaned.head()

,job_id,company_name,job_title,job_description,max_salary,pay_period,location,company_id,views,med_salary,...,skills_desc,listed_time,posting_domain,sponsored,work_type,currency,compensation_type,normalized_salary,zip_code,fips
0,921716,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,20.0,HOURLY,"Princeton, NJ",2774458.0,20.0,NaN,...,Requirements: \n\nWe are seeking a College or ...,1.713398e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,38480.0,8540.0,34021.0
1,1829192,NaN,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committ...",50.0,HOURLY,"Fort Collins, CO",NaN,1.0,NaN,...,NaN,1.712858e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,83200.0,80521.0,8069.0
2,10998357,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,65000.0,YEARLY,"Cincinnati, OH",64896719.0,8.0,NaN,...,We are currently accepting resumes for FOH - A...,1.713278e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,55000.0,45202.0,39061.0
3,23221523,"Abrams Fensterman, LLP",Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,175000.0,YEARLY,"New Hyde Park, NY",766262.0,16.0,NaN,...,This position requires a baseline understandin...,1.712896e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,11040.0,36059.0
4,35982263,NaN,Service Technician,Looking for HVAC service tech with experience ...,80000.0,YEARLY,"Burlington, IA",NaN,3.0,NaN,...,NaN,1.713452e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,70000.0,52601.0,19057.0

In [19]:
posting_cleaned.dtypes

job_id                          int64
company_name                   object
job_title                      object
job_description                object
max_salary                    float64
pay_period                     object
location                       object
company_id                    float64
views                         float64
med_salary                    float64
min_salary                    float64
formatted_work_type            object
num_applicants                float64
original_listed_time          float64
remote_allowed                float64
job_posting_url                object
application_url                object
application_type               object
expiry                        float64
closed_time                   float64
formatted_experience_level     object
skills_desc                    object
listed_time                   float64
posting_domain                 object
sponsored                       int64
work_type                      object
currency                       object
compensation_type              object
normalized_salary             float64
zip_code                      float64
fips                          float64
dtype: object

In [22]:
posting_cleaned['zip_code']=posting_cleaned['fips'].astype('str')

In [20]:
posting_cleaned=posting_cleaned.astype({'zip_code': 'str' ,'fips': 'str'})

In [21]:
posting_cleaned.dtypes

job_id                          int64
company_name                   object
job_title                      object
job_description                object
max_salary                    float64
pay_period                     object
location                       object
company_id                    float64
views                         float64
med_salary                    float64
min_salary                    float64
formatted_work_type            object
num_applicants                float64
original_listed_time          float64
remote_allowed                float64
job_posting_url                object
application_url                object
application_type               object
expiry                        float64
closed_time                   float64
formatted_experience_level     object
skills_desc                    object
listed_time                   float64
posting_domain                 object
sponsored                       int64
work_type                      object
currency                       object
compensation_type              object
normalized_salary             float64
zip_code                       object
fips                           object
dtype: object

In [23]:
posting_cleaned.drop(['med_salary','closed_time', 'skills_desc'], axis=1, inplace=True)

In [26]:
posting_cleaned.columns

Index(['job_id', 'company_name', 'job_title', 'job_description', 'max_salary',
       'pay_period', 'location', 'company_id', 'views', 'min_salary',
       'formatted_work_type', 'num_applicants', 'original_listed_time',
       'remote_allowed', 'job_posting_url', 'application_url',
       'application_type', 'expiry', 'formatted_experience_level',
       'listed_time', 'posting_domain', 'sponsored', 'work_type', 'currency',
       'compensation_type', 'normalized_salary', 'zip_code', 'fips'],
      dtype='object')

In [27]:
posting_cleaned['job_title']=posting_cleaned['job_title'].str.strip()

In [28]:
posting_cleaned['job_title']=posting_cleaned['job_title'].str.lower()

In [29]:
posting_cleaned['job_title']

0                                     marketing coordinator
1                         mental health therapist/counselor
2                               assitant restaurant manager
3         senior elder law / trusts and estates associat...
4                                        service technician
                                ...
123844                     title ix/investigations attorney
123845         staff software engineer, ml serving platform
123846                 account executive, oregon/washington
123847                         business development manager
123848                    marketing social media specialist
Name: job_title, Length: 123849, dtype: object

In [30]:
posting_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 123849 entries, 0 to 123848
Data columns (total 28 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   job_id                      123849 non-null  int64
 1   company_name                122130 non-null  object
 2   job_title                   123849 non-null  object
 3   job_description             123842 non-null  object
 4   max_salary                  29793 non-null   float64
 5   pay_period                  36073 non-null   object
 6   location                    123849 non-null  object
 7   company_id                  122132 non-null  float64
 8   views                       122160 non-null  float64
 9   min_salary                  29793 non-null   float64
 10  formatted_work_type         123849 non-null  object
 11  num_applicants              23320 non-null   float64
 12  original_listed_time        123849 non-null  float64
 13  remote_allowed              15246 non-null   float64
 14  job_posting_url             123849 non-null  object
 15  application_url             87184 non-null   object
 16  application_type            123849 non-null  object
 17  expiry                      123849 non-null  float64
 18  formatted_experience_level  94440 non-null   object
 19  listed_time                 123849 non-null  float64
 20  posting_domain              83881 non-null   object
 21  sponsored                   123849 non-null  int64
 22  work_type                   123849 non-null  object
 23  currency                    36073 non-null   object
 24  compensation_type           36073 non-null   object
 25  normalized_salary           36073 non-null   float64
 26  zip_code                    123849 non-null  object
 27  fips                        123849 non-null  object
dtypes: float64(10), int64(2), object(16)
memory usage: 26.5+ MB

In [31]:
posting_cleaned['remote_allowed'].unique()

array([nan,  1.])

In [9]:
posting_cleaned['remote_allowed'].fillna(0,inplace=True)

In [8]:
posting_cleaned['remote_allowed'].unique()

array([nan,  1.])

In [11]:
posting_cleaned['remote_allowed']=posting_cleaned['remote_allowed'].astype('int')
posting_cleaned['remote_allowed'].unique()

array([0, 1])

In [6]:
posting_cleaned.dropna(axis=0, how='all', inplace=True)

In [7]:
posting_cleaned.shape

(123849, 31)

In [8]:
posting_cleaned.shape

(123849, 31)

In [9]:
posting_cleaned.dropna(axis=0, subset=['company_name'], inplace=True)

In [10]:
posting_cleaned.shape

(122130, 31)

In [17]:
posting_cleaned=pd.concat([posting_cleaned, posting_cleaned.iloc[0:2]],ignore_index=True)
posting_cleaned=pd.concat([posting_cleaned, posting_cleaned.iloc[1000:1002]],ignore_index=True)
posting_cleaned=pd.concat([posting_cleaned, posting_cleaned.iloc[10000:10002]],ignore_index=True)

In [18]:
posting_cleaned.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
122131     True
122132     True
122133     True
122134     True
122135     True
Length: 122136, dtype: bool

In [20]:
posting_cleaned[posting_cleaned.duplicated(keep=False)]

,job_id,company_name,title,description,max_salary,pay_period,location,company_id,views,med_salary,...,skills_desc,listed_time,posting_domain,sponsored,work_type,currency,compensation_type,normalized_salary,zip_code,fips
0,921716,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,20.0,HOURLY,"Princeton, NJ",2774458.0,20.0,NaN,...,Requirements: \n\nWe are seeking a College or ...,1.713398e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,38480.0,8540.0,34021.0
1,10998357,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,65000.0,YEARLY,"Cincinnati, OH",64896719.0,8.0,NaN,...,We are currently accepting resumes for FOH - A...,1.713278e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,55000.0,45202.0,39061.0
1000,3884433264,Midea America Corp,Manager - Digital Marketing,Midea Group is one of the world’s largest home...,135000.0,YEARLY,"Parsippany, NJ",1230481.0,54.0,NaN,...,NaN,1.712346e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,122500.0,7054.0,34027.0
1001,3884433270,Insight Global,Installation Engineer,Must Haves:-2+ years of Automation Engineering...,40.0,HOURLY,"Rochester, MI",11056.0,8.0,NaN,...,NaN,1.712346e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,72800.0,48306.0,NaN
10000,3886884660,XL Pro Staffing and Consulting Group,Traffic Coordinator,Vision Statement:At XL Pro Staffing & Consulti...,NaN,HOURLY,"Irving, TX",9391120.0,7.0,16.5,...,NaN,1.712666e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,34320.0,75038.0,48113.0
10001,3886884692,XL Pro Staffing and Consulting Group,Shipping and Receiving Specialist,Vision Statement:At XL Pro Staffing & Consulti...,NaN,HOURLY,"Lewisville, TX",9391120.0,6.0,19.5,...,NaN,1.712666e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,40560.0,75057.0,48121.0
122130,921716,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,20.0,HOURLY,"Princeton, NJ",2774458.0,20.0,NaN,...,Requirements: \n\nWe are seeking a College or ...,1.713398e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,38480.0,8540.0,34021.0
122131,10998357,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,65000.0,YEARLY,"Cincinnati, OH",64896719.0,8.0,NaN,...,We are currently accepting resumes for FOH - A...,1.713278e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,55000.0,45202.0,39061.0
122132,3884433264,Midea America Corp,Manager - Digital Marketing,Midea Group is one of the world’s largest home...,135000.0,YEARLY,"Parsippany, NJ",1230481.0,54.0,NaN,...,NaN,1.712346e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,122500.0,7054.0,34027.0
122133,3884433270,Insight Global,Installation Engineer,Must Haves:-2+ years of Automation Engineering...,40.0,HOURLY,"Rochester, MI",11056.0,8.0,NaN,...,NaN,1.712346e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,72800.0,48306.0,NaN
122134,3886884660,XL Pro Staffing and Consulting Group,Traffic Coordinator,Vision Statement:At XL Pro Staffing & Consulti...,NaN,HOURLY,"Irving, TX",9391120.0,7.0,16.5,...,NaN,1.712666e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,34320.0,75038.0,48113.0
122135,3886884692,XL Pro Staffing and Consulting Group,Shipping and Receiving Specialist,Vision Statement:At XL Pro Staffing & Consulti...,NaN,HOURLY,"Lewisville, TX",9391120.0,6.0,19.5,...,NaN,1.712666e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,40560.0,75057.0,48121.0

In [22]:
posting_cleaned.drop_duplicates(inplace=True)

In [23]:
posting_cleaned[posting_cleaned.duplicated()]

Empty DataFrame
Columns: [job_id, company_name, title, description, max_salary, pay_period, location, company_id, views, med_salary, min_salary, formatted_work_type, applies, original_listed_time, remote_allowed, job_posting_url, application_url, application_type, expiry, closed_time, formatted_experience_level, skills_desc, listed_time, posting_domain, sponsored, work_type, currency, compensation_type, normalized_salary, zip_code, fips]
Index: []

[0 rows x 31 columns]

In [6]:
posting_cleaned[posting_cleaned['max_salary']>= 50000]

,job_id,company_name,title,description,max_salary,pay_period,location,company_id,views,med_salary,...,skills_desc,listed_time,posting_domain,sponsored,work_type,currency,compensation_type,normalized_salary,zip_code,fips
2,10998357,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,65000.0,YEARLY,"Cincinnati, OH",64896719.0,8.0,NaN,...,We are currently accepting resumes for FOH - A...,1.713278e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,55000.0,45202.0,39061.0
3,23221523,"Abrams Fensterman, LLP",Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,175000.0,YEARLY,"New Hyde Park, NY",766262.0,16.0,NaN,...,This position requires a baseline understandin...,1.712896e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,11040.0,36059.0
4,35982263,NaN,Service Technician,Looking for HVAC service tech with experience ...,80000.0,YEARLY,"Burlington, IA",NaN,3.0,NaN,...,NaN,1.713452e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,70000.0,52601.0,19057.0
6,103254301,Raw Cereal,Producer,Company DescriptionRaw Cereal is a creative de...,300000.0,YEARLY,United States,81942316.0,7.0,NaN,...,NaN,1.712861e+12,NaN,0,CONTRACT,USD,BASE_SALARY,180000.0,NaN,NaN
7,112576855,NaN,Building Engineer,Summary: Due to the pending retirement of our ...,120000.0,YEARLY,"San Francisco, CA",NaN,2.0,NaN,...,NaN,1.712443e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,105000.0,94101.0,6075.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123834,3906265332,Lozano Smith,Litigation Legal Secretary,We currently have an opening in our Sacramento...,90000.0,YEARLY,"Sacramento, CA",56120.0,2.0,NaN,...,NaN,1.713572e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,67500.0,95811.0,6067.0
123836,3906265349,Lozano Smith,Labor & Employment Attorney,Lozano Smith’s Fresno office is seeking a tale...,195000.0,YEARLY,"Fresno County, CA",56120.0,1.0,NaN,...,NaN,1.713573e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,93650.0,6019.0
123839,3906266165,Athena Recruiting,Catering Event Manager,This role handles all the onsite catering and ...,65000.0,YEARLY,Greater Indianapolis,3056329.0,3.0,NaN,...,NaN,1.713571e+12,NaN,0,PART_TIME,USD,BASE_SALARY,57500.0,NaN,NaN
123844,3906267117,Lozano Smith,Title IX/Investigations Attorney,Our Walnut Creek office is currently seeking a...,195000.0,YEARLY,"Walnut Creek, CA",56120.0,1.0,NaN,...,NaN,1.713571e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,94595.0,6013.0
123848,3906267224,Solugenix,Marketing Social Media Specialist,Marketing Social Media Specialist - $70k – $75...,75000.0,YEARLY,"San Juan Capistrano, CA",43325.0,2.0,NaN,...,NaN,1.713573e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,72500.0,92675.0,6059.0

In [7]:
posting_cleaned[(posting_cleaned['work_type'] == 'FULL_TIME') & (posting_cleaned['currency'] == 'USD')]

,job_id,company_name,title,description,max_salary,pay_period,location,company_id,views,med_salary,...,skills_desc,listed_time,posting_domain,sponsored,work_type,currency,compensation_type,normalized_salary,zip_code,fips
0,921716,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,20.0,HOURLY,"Princeton, NJ",2774458.0,20.0,NaN,...,Requirements: \n\nWe are seeking a College or ...,1.713398e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,38480.0,8540.0,34021.0
1,1829192,NaN,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committ...",50.0,HOURLY,"Fort Collins, CO",NaN,1.0,NaN,...,NaN,1.712858e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,83200.0,80521.0,8069.0
2,10998357,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,65000.0,YEARLY,"Cincinnati, OH",64896719.0,8.0,NaN,...,We are currently accepting resumes for FOH - A...,1.713278e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,55000.0,45202.0,39061.0
3,23221523,"Abrams Fensterman, LLP",Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,175000.0,YEARLY,"New Hyde Park, NY",766262.0,16.0,NaN,...,This position requires a baseline understandin...,1.712896e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,11040.0,36059.0
4,35982263,NaN,Service Technician,Looking for HVAC service tech with experience ...,80000.0,YEARLY,"Burlington, IA",NaN,3.0,NaN,...,NaN,1.713452e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,70000.0,52601.0,19057.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123832,3906265303,SPS,Client Services Associate (42181),Job Title: Client Services Associate\n\n Repo...,18.0,HOURLY,"Nashville, TN",146075.0,3.0,NaN,...,NaN,1.713573e+12,www.paycomonline.net,0,FULL_TIME,USD,BASE_SALARY,37440.0,37201.0,47037.0
123834,3906265332,Lozano Smith,Litigation Legal Secretary,We currently have an opening in our Sacramento...,90000.0,YEARLY,"Sacramento, CA",56120.0,2.0,NaN,...,NaN,1.713572e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,67500.0,95811.0,6067.0
123836,3906265349,Lozano Smith,Labor & Employment Attorney,Lozano Smith’s Fresno office is seeking a tale...,195000.0,YEARLY,"Fresno County, CA",56120.0,1.0,NaN,...,NaN,1.713573e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,93650.0,6019.0
123844,3906267117,Lozano Smith,Title IX/Investigations Attorney,Our Walnut Creek office is currently seeking a...,195000.0,YEARLY,"Walnut Creek, CA",56120.0,1.0,NaN,...,NaN,1.713571e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,94595.0,6013.0
123848,3906267224,Solugenix,Marketing Social Media Specialist,Marketing Social Media Specialist - $70k – $75...,75000.0,YEARLY,"San Juan Capistrano, CA",43325.0,2.0,NaN,...,NaN,1.713573e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,72500.0,92675.0,6059.0

In [11]:
posting_cleaned_filtered = posting_cleaned[(posting_cleaned['work_type'] == 'FULL_TIME') & (posting_cleaned['currency'] == 'USD')]

In [12]:
posting_cleaned_filtered

,job_id,company_name,job_title,job_description,max_salary,pay_period,location,company_id,views,med_salary,...,skills_desc,listed_time,posting_domain,sponsored,work_type,currency,compensation_type,normalized_salary,zip_code,fips
0,921716,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,20.0,HOURLY,"Princeton, NJ",2774458.0,20.0,NaN,...,Requirements: \n\nWe are seeking a College or ...,1.713398e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,38480.0,8540.0,34021.0
2,10998357,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,65000.0,YEARLY,"Cincinnati, OH",64896719.0,8.0,NaN,...,We are currently accepting resumes for FOH - A...,1.713278e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,55000.0,45202.0,39061.0
3,23221523,"Abrams Fensterman, LLP",Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,175000.0,YEARLY,"New Hyde Park, NY",766262.0,16.0,NaN,...,This position requires a baseline understandin...,1.712896e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,11040.0,36059.0
16,95428182,CLEVELAND KIDS BOOK BANK,Administrative Coordinator,Job Title: Administrative CoordinatorOrganizat...,NaN,HOURLY,"Cleveland, OH",55624331.0,1.0,25.0,...,NaN,1.712856e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,52000.0,44102.0,39035.0
35,266566927,Revesco Properties,Marketing & Office Coordinator,About Revesco Properties:Revesco Properties is...,75000.0,YEARLY,"Denver, CO",8577252.0,13.0,NaN,...,NaN,1.713459e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,65000.0,80202.0,8031.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123832,3906265303,SPS,Client Services Associate (42181),Job Title: Client Services Associate\n\n Repo...,18.0,HOURLY,"Nashville, TN",146075.0,3.0,NaN,...,NaN,1.713573e+12,www.paycomonline.net,0,FULL_TIME,USD,BASE_SALARY,37440.0,37201.0,47037.0
123834,3906265332,Lozano Smith,Litigation Legal Secretary,We currently have an opening in our Sacramento...,90000.0,YEARLY,"Sacramento, CA",56120.0,2.0,NaN,...,NaN,1.713572e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,67500.0,95811.0,6067.0
123836,3906265349,Lozano Smith,Labor & Employment Attorney,Lozano Smith’s Fresno office is seeking a tale...,195000.0,YEARLY,"Fresno County, CA",56120.0,1.0,NaN,...,NaN,1.713573e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,93650.0,6019.0
123844,3906267117,Lozano Smith,Title IX/Investigations Attorney,Our Walnut Creek office is currently seeking a...,195000.0,YEARLY,"Walnut Creek, CA",56120.0,1.0,NaN,...,NaN,1.713571e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,94595.0,6013.0
123848,3906267224,Solugenix,Marketing Social Media Specialist,Marketing Social Media Specialist - $70k – $75...,75000.0,YEARLY,"San Juan Capistrano, CA",43325.0,2.0,NaN,...,NaN,1.713573e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,72500.0,92675.0,6059.0

In [16]:
posting_cleaned_filtered = posting_cleaned_filtered[posting_cleaned_filtered['title'].str.contains('data', case=False)]

In [13]:
posting_cleaned_filtered.head()

,job_id,company_name,job_title,job_description,max_salary,pay_period,location,company_id,views,med_salary,...,skills_desc,listed_time,posting_domain,sponsored,work_type,currency,compensation_type,normalized_salary,zip_code,fips
0,921716,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,20.0,HOURLY,"Princeton, NJ",2774458.0,20.0,NaN,...,Requirements: \n\nWe are seeking a College or ...,1.713398e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,38480.0,8540.0,34021.0
2,10998357,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,65000.0,YEARLY,"Cincinnati, OH",64896719.0,8.0,NaN,...,We are currently accepting resumes for FOH - A...,1.713278e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,55000.0,45202.0,39061.0
3,23221523,"Abrams Fensterman, LLP",Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,175000.0,YEARLY,"New Hyde Park, NY",766262.0,16.0,NaN,...,This position requires a baseline understandin...,1.712896e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,11040.0,36059.0
16,95428182,CLEVELAND KIDS BOOK BANK,Administrative Coordinator,Job Title: Administrative CoordinatorOrganizat...,NaN,HOURLY,"Cleveland, OH",55624331.0,1.0,25.0,...,NaN,1.712856e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,52000.0,44102.0,39035.0
35,266566927,Revesco Properties,Marketing & Office Coordinator,About Revesco Properties:Revesco Properties is...,75000.0,YEARLY,"Denver, CO",8577252.0,13.0,NaN,...,NaN,1.713459e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,65000.0,80202.0,8031.0

In [14]:
posting_cleaned.query('max_salary > 100000 and remote_allowed == 1', inplace=True)

In [15]:
posting_cleaned.head()

,job_id,company_name,job_title,job_description,max_salary,pay_period,location,company_id,views,med_salary,...,skills_desc,listed_time,posting_domain,sponsored,work_type,currency,compensation_type,normalized_salary,zip_code,fips
6,103254301,Raw Cereal,Producer,Company DescriptionRaw Cereal is a creative de...,300000.0,YEARLY,United States,81942316.0,7.0,NaN,...,NaN,1.712861e+12,NaN,0,CONTRACT,USD,BASE_SALARY,180000.0,NaN,NaN
191,3610032286,HirelyAI,Sales Development Representative,Position Summary:This is a 100% commission bas...,130813.0,YEARLY,"Oregon, United States",91423287.0,10.0,NaN,...,NaN,1.712347e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,65407.0,NaN,NaN
339,3787503302,Bend the Arc: A Jewish Partnership for Justice,Associate Director of Individual Giving,FULL JOB POSTING AT: https://www.bendthearc.us...,107000.0,YEARLY,United States,2543509.0,67.0,NaN,...,NaN,1.712350e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,101000.0,NaN,NaN
374,3803055615,"Five Rings Financial, LLC",Financial Services Representative,This role is a Regional Manager for Five Rings...,250000.0,YEARLY,United States,2434847.0,46.0,NaN,...,NaN,1.713458e+12,NaN,0,CONTRACT,USD,BASE_SALARY,125002.5,NaN,NaN
445,3831919828,Riteload,Sales Executive,Shipper Sales Executive\nJob Title: Shipper Sa...,400000.0,YEARLY,United States,40739036.0,4.0,NaN,...,NaN,1.712447e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,300000.0,NaN,NaN

In [22]:
pd.set_option('display.max_columns', None)
posting_cleaned.head()

,job_id,company_name,job_title,job_description,max_salary,pay_period,location,company_id,views,med_salary,min_salary,formatted_work_type,num_applicants,original_listed_time,remote_allowed,job_posting_url,application_url,application_type,expiry,closed_time,formatted_experience_level,skills_desc,listed_time,posting_domain,sponsored,work_type,currency,compensation_type,normalized_salary,zip_code,fips
6,103254301,Raw Cereal,Producer,Company DescriptionRaw Cereal is a creative de...,300000.0,YEARLY,United States,81942316.0,7.0,NaN,60000.0,Contract,1.0,1.712861e+12,1.0,https://www.linkedin.com/jobs/view/103254301/?...,NaN,SimpleOnsiteApply,1.715453e+12,NaN,NaN,NaN,1.712861e+12,NaN,0,CONTRACT,USD,BASE_SALARY,180000.0,NaN,NaN
191,3610032286,HirelyAI,Sales Development Representative,Position Summary:This is a 100% commission bas...,130813.0,YEARLY,"Oregon, United States",91423287.0,10.0,NaN,1.0,Full-time,2.0,1.712347e+12,1.0,https://www.linkedin.com/jobs/view/3610032286/...,https://hirelyai.com/hirely-pro?interviewCode=...,OffsiteApply,1.714939e+12,NaN,NaN,NaN,1.712347e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,65407.0,NaN,NaN
339,3787503302,Bend the Arc: A Jewish Partnership for Justice,Associate Director of Individual Giving,FULL JOB POSTING AT: https://www.bendthearc.us...,107000.0,YEARLY,United States,2543509.0,67.0,NaN,95000.0,Full-time,15.0,1.712350e+12,1.0,https://www.linkedin.com/jobs/view/3787503302/...,NaN,ComplexOnsiteApply,1.714942e+12,NaN,NaN,NaN,1.712350e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,101000.0,NaN,NaN
374,3803055615,"Five Rings Financial, LLC",Financial Services Representative,This role is a Regional Manager for Five Rings...,250000.0,YEARLY,United States,2434847.0,46.0,NaN,5.0,Contract,3.0,1.713458e+12,1.0,https://www.linkedin.com/jobs/view/3803055615/...,NaN,ComplexOnsiteApply,1.716050e+12,NaN,NaN,NaN,1.713458e+12,NaN,0,CONTRACT,USD,BASE_SALARY,125002.5,NaN,NaN
445,3831919828,Riteload,Sales Executive,Shipper Sales Executive\nJob Title: Shipper Sa...,400000.0,YEARLY,United States,40739036.0,4.0,NaN,200000.0,Full-time,NaN,1.712447e+12,1.0,https://www.linkedin.com/jobs/view/3831919828/...,NaN,ComplexOnsiteApply,1.715039e+12,NaN,NaN,NaN,1.712447e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,300000.0,NaN,NaN

In [23]:
posting_cleaned.rename({'title': 'job_title', 'description': 'job_description'}, axis=1, inplace=True)

In [16]:
posting_cleaned_filtered.head()

,job_id,company_name,job_title,job_description,max_salary,pay_period,location,company_id,views,med_salary,...,skills_desc,listed_time,posting_domain,sponsored,work_type,currency,compensation_type,normalized_salary,zip_code,fips
0,921716,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,20.0,HOURLY,"Princeton, NJ",2774458.0,20.0,NaN,...,Requirements: \n\nWe are seeking a College or ...,1.713398e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,38480.0,8540.0,34021.0
2,10998357,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,65000.0,YEARLY,"Cincinnati, OH",64896719.0,8.0,NaN,...,We are currently accepting resumes for FOH - A...,1.713278e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,55000.0,45202.0,39061.0
3,23221523,"Abrams Fensterman, LLP",Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,175000.0,YEARLY,"New Hyde Park, NY",766262.0,16.0,NaN,...,This position requires a baseline understandin...,1.712896e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,11040.0,36059.0
16,95428182,CLEVELAND KIDS BOOK BANK,Administrative Coordinator,Job Title: Administrative CoordinatorOrganizat...,NaN,HOURLY,"Cleveland, OH",55624331.0,1.0,25.0,...,NaN,1.712856e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,52000.0,44102.0,39035.0
35,266566927,Revesco Properties,Marketing & Office Coordinator,About Revesco Properties:Revesco Properties is...,75000.0,YEARLY,"Denver, CO",8577252.0,13.0,NaN,...,NaN,1.713459e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,65000.0,80202.0,8031.0

In [17]:
posting_cleaned_filtered.set_index('job_id', inplace=True)

#  iloc= numeric index for dataframe
#  loc= label index of the dataframe
both ways of selecting rows from dataframe
posting_cleaned_filtered.loc[1]=first row
posting_cleaned_filtered.iloc[1]=second row

In [19]:
posting_cleaned_filtered.loc[921716]

company_name                                              Corcoran Sawyer Smith
job_title                                                 Marketing Coordinator
job_description               Job descriptionA leading real estate firm in N...
max_salary                                                                 20.0
pay_period                                                               HOURLY
location                                                          Princeton, NJ
company_id                                                            2774458.0
views                                                                      20.0
med_salary                                                                  NaN
min_salary                                                                 17.0
formatted_work_type                                                   Full-time
num_applicants                                                              2.0
original_listed_time                                            1713397508000.0
remote_allowed                                                              NaN
job_posting_url               https://www.linkedin.com/jobs/view/921716/?trk...
application_url                                                             NaN
application_type                                             ComplexOnsiteApply
expiry                                                          1715989508000.0
closed_time                                                                 NaN
formatted_experience_level                                                  NaN
skills_desc                   Requirements: \n\nWe are seeking a College or ...
listed_time                                                     1713397508000.0
posting_domain                                                              NaN
sponsored                                                                     0
work_type                                                             FULL_TIME
currency                                                                    USD
compensation_type                                                   BASE_SALARY
normalized_salary                                                       38480.0
zip_code                                                                 8540.0
fips                                                                    34021.0
Name: 921716, dtype: object

In [20]:
posting_cleaned_filtered.iloc[0]

company_name                                              Corcoran Sawyer Smith
job_title                                                 Marketing Coordinator
job_description               Job descriptionA leading real estate firm in N...
max_salary                                                                 20.0
pay_period                                                               HOURLY
location                                                          Princeton, NJ
company_id                                                            2774458.0
views                                                                      20.0
med_salary                                                                  NaN
min_salary                                                                 17.0
formatted_work_type                                                   Full-time
num_applicants                                                              2.0
original_listed_time                                            1713397508000.0
remote_allowed                                                              NaN
job_posting_url               https://www.linkedin.com/jobs/view/921716/?trk...
application_url                                                             NaN
application_type                                             ComplexOnsiteApply
expiry                                                          1715989508000.0
closed_time                                                                 NaN
formatted_experience_level                                                  NaN
skills_desc                   Requirements: \n\nWe are seeking a College or ...
listed_time                                                     1713397508000.0
posting_domain                                                              NaN
sponsored                                                                     0
work_type                                                             FULL_TIME
currency                                                                    USD
compensation_type                                                   BASE_SALARY
normalized_salary                                                       38480.0
zip_code                                                                 8540.0
fips                                                                    34021.0
Name: 921716, dtype: object

In [23]:
posting_cleaned_filtered.loc[posting_cleaned_filtered['remote_allowed'] == 1]

,company_name,job_title,job_description,max_salary,pay_period,location,company_id,views,med_salary,min_salary,formatted_work_type,num_applicants,original_listed_time,remote_allowed,job_posting_url,application_url,application_type,expiry,closed_time,formatted_experience_level,skills_desc,listed_time,posting_domain,sponsored,work_type,currency,compensation_type,normalized_salary,zip_code,fips
job_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1014822088,Tracker,Marketing Specialist,About TrackerTracker is a leading global cloud...,80000.0,YEARLY,United States,255252.0,7.0,NaN,70000.0,Full-time,2.0,1.713469e+12,1.0,https://www.linkedin.com/jobs/view/1014822088/...,NaN,ComplexOnsiteApply,1.716061e+12,NaN,NaN,NaN,1.713469e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,75000.0,NaN,NaN
1826257634,The Medicare Coach,Social Security Specialist / Retirement Benefi...,Do you have a background in the Social Securit...,25.0,HOURLY,"Colorado, United States",35690006.0,60.0,NaN,19.0,Full-time,7.0,1.713214e+12,1.0,https://www.linkedin.com/jobs/view/1826257634/...,NaN,ComplexOnsiteApply,1.715806e+12,NaN,NaN,NaN,1.713214e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,45760.0,NaN,NaN
3277232283,KLA (Kim Lundgren Associates),HR & Administrative Assistant,HR & Administrative CoordinatorWork is Remote ...,72000.0,YEARLY,United States,70819018.0,59.0,NaN,55000.0,Full-time,18.0,1.712893e+12,1.0,https://www.linkedin.com/jobs/view/3277232283/...,https://jobs.gusto.com/postings/kim-lundgren-a...,OffsiteApply,1.715485e+12,NaN,NaN,NaN,1.712893e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,63500.0,NaN,NaN
3447180215,Ameriflex,Client Relationship Specialist,Think you have what it takes to be a top perfo...,NaN,YEARLY,United States,532049.0,14.0,45000.0,NaN,Full-time,NaN,1.713212e+12,1.0,https://www.linkedin.com/jobs/view/3447180215/...,https://theapplicantmanager.com/jobs?pos=aa111,OffsiteApply,1.715804e+12,1.713212e+12,NaN,NaN,1.713212e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,45000.0,NaN,NaN
3580545157,Action Equipment and Scaffold Company,Industrial Business Development Manager,Company DescriptionAction Equipment and Scaffo...,100000.0,YEARLY,United States,3325877.0,3.0,NaN,50000.0,Full-time,NaN,1.713564e+12,1.0,https://www.linkedin.com/jobs/view/3580545157/...,NaN,ComplexOnsiteApply,1.716156e+12,NaN,NaN,NaN,1.713564e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,75000.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3906260083,Circle,Senior Enablement Lead,Circle is a financial technology company at th...,120000.0,YEARLY,"Phoenix, AZ",3509899.0,2.0,NaN,90000.0,Full-time,NaN,1.713485e+12,1.0,https://www.linkedin.com/jobs/view/3906260083/...,https://boards.greenhouse.io/circle/jobs/73416...,OffsiteApply,1.716160e+12,NaN,Mid-Senior level,NaN,1.713568e+12,boards.greenhouse.io,0,FULL_TIME,USD,BASE_SALARY,105000.0,85003.0,4013.0
3906260210,National Federation of Independent Business (N...,Outside Sales Representative,Overview\n\nDo you have a passion for making a...,200000.0,YEARLY,"Poplar Bluff, MO",12332.0,3.0,NaN,70000.0,Full-time,NaN,1.713485e+12,1.0,https://www.linkedin.com/jobs/view/3906260210/...,https://careers.nfib.com/jobs/7467?mode=apply&...,OffsiteApply,1.716160e+12,NaN,Entry level,NaN,1.713568e+12,careers.nfib.com,0,FULL_TIME,USD,BASE_SALARY,135000.0,63901.0,29023.0
3906260410,Madison Black,"Scientific Director, Medical Communications",This role is responsible for the strategic dir...,170000.0,YEARLY,United States,10573666.0,2.0,NaN,130000.0,Full-time,1.0,1.713569e+12,1.0,https://www.linkedin.com/jobs/view/3906260410/...,https://www.aplitrak.com/?adid=TFJDTy4wNTM4Ni4...,OffsiteApply,1.716161e+12,NaN,Director,NaN,1.713569e+12,www.aplitrak.com,0,FULL_TIME,USD,BASE_SALARY,150000.0,NaN,NaN
3906260985,The Gaines Agency,Remote Business Development Expert (Average $7...,"At The Gaines Agency, we are committed to ever...",200000.0,YEARLY,United States,90408525.0,2.0,NaN,75000.0,Full-time,NaN,1.713572e+12,1.0,https://www.linkedin.com/jobs/view/3906260985/...,NaN,ComplexOnsiteApply,1.716164e+12,NaN,NaN,NaN,1.713572e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,137500.0,NaN,NaN
3906263199,Applicantz,Cloud Domain Architect,This is a full time job with our Fortune clien...,150000.0,YEARLY,"Houston, TX",24629.0,NaN,NaN,125000.0,Full-time,NaN,1.713571e+12,1.0,https://www.linkedin.com/jobs/view/3906263199/...,NaN,ComplexOnsiteApply,1.716163e+12,NaN,Mid-Senior level,NaN,1.713571e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,137500.0,77002.0,48201.0

In [24]:
posting_cleaned_filtered.loc[posting_cleaned_filtered['remote_allowed'] == 1, ['job_title', 'remote_allowed']]

                                                    job_title  remote_allowed
job_id
1014822088                               Marketing Specialist             1.0
1826257634  Social Security Specialist / Retirement Benefi...             1.0
3277232283                      HR & Administrative Assistant             1.0
3447180215                     Client Relationship Specialist             1.0
3580545157            Industrial Business Development Manager             1.0
...                                                       ...             ...
3906260083                             Senior Enablement Lead             1.0
3906260210                       Outside Sales Representative             1.0
3906260410        Scientific Director, Medical Communications             1.0
3906260985  Remote Business Development Expert (Average $7...             1.0
3906263199                             Cloud Domain Architect             1.0

[3655 rows x 2 columns]

In [26]:
posting_cleaned_filtered.reset_index(inplace=True)
posting_cleaned_filtered

,index,job_id,company_name,job_title,job_description,max_salary,pay_period,location,company_id,views,med_salary,min_salary,formatted_work_type,num_applicants,original_listed_time,remote_allowed,job_posting_url,application_url,application_type,expiry,closed_time,formatted_experience_level,skills_desc,listed_time,posting_domain,sponsored,work_type,currency,compensation_type,normalized_salary,zip_code,fips
0,0,921716,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,20.0,HOURLY,"Princeton, NJ",2774458.0,20.0,NaN,17.0,Full-time,2.0,1.713398e+12,NaN,https://www.linkedin.com/jobs/view/921716/?trk...,NaN,ComplexOnsiteApply,1.715990e+12,NaN,NaN,Requirements: \n\nWe are seeking a College or ...,1.713398e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,38480.0,8540.0,34021.0
1,1,10998357,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,65000.0,YEARLY,"Cincinnati, OH",64896719.0,8.0,NaN,45000.0,Full-time,NaN,1.713278e+12,NaN,https://www.linkedin.com/jobs/view/10998357/?t...,NaN,ComplexOnsiteApply,1.715870e+12,NaN,NaN,We are currently accepting resumes for FOH - A...,1.713278e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,55000.0,45202.0,39061.0
2,2,23221523,"Abrams Fensterman, LLP",Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,175000.0,YEARLY,"New Hyde Park, NY",766262.0,16.0,NaN,140000.0,Full-time,NaN,1.712896e+12,NaN,https://www.linkedin.com/jobs/view/23221523/?t...,NaN,ComplexOnsiteApply,1.715488e+12,NaN,NaN,This position requires a baseline understandin...,1.712896e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,11040.0,36059.0
3,3,95428182,CLEVELAND KIDS BOOK BANK,Administrative Coordinator,Job Title: Administrative CoordinatorOrganizat...,NaN,HOURLY,"Cleveland, OH",55624331.0,1.0,25.0,NaN,Full-time,NaN,1.712856e+12,NaN,https://www.linkedin.com/jobs/view/95428182/?t...,https://www.kidsbookbank.org/employment/,OffsiteApply,1.715448e+12,NaN,NaN,NaN,1.712856e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,52000.0,44102.0,39035.0
4,4,266566927,Revesco Properties,Marketing & Office Coordinator,About Revesco Properties:Revesco Properties is...,75000.0,YEARLY,"Denver, CO",8577252.0,13.0,NaN,55000.0,Full-time,1.0,1.713459e+12,NaN,https://www.linkedin.com/jobs/view/266566927/?...,NaN,SimpleOnsiteApply,1.716051e+12,NaN,NaN,NaN,1.713459e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,65000.0,80202.0,8031.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28733,28733,3906265303,SPS,Client Services Associate (42181),Job Title: Client Services Associate\n\n Repo...,18.0,HOURLY,"Nashville, TN",146075.0,3.0,NaN,18.0,Full-time,NaN,1.713572e+12,NaN,https://www.linkedin.com/jobs/view/3906265303/...,https://www.paycomonline.net/v4/ats/web.php/jo...,OffsiteApply,1.716165e+12,NaN,Entry level,NaN,1.713573e+12,www.paycomonline.net,0,FULL_TIME,USD,BASE_SALARY,37440.0,37201.0,47037.0
28734,28734,3906265332,Lozano Smith,Litigation Legal Secretary,We currently have an opening in our Sacramento...,90000.0,YEARLY,"Sacramento, CA",56120.0,2.0,NaN,45000.0,Full-time,NaN,1.713572e+12,NaN,https://www.linkedin.com/jobs/view/3906265332/...,NaN,ComplexOnsiteApply,1.716164e+12,NaN,Associate,NaN,1.713572e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,67500.0,95811.0,6067.0
28735,28735,3906265349,Lozano Smith,Labor & Employment Attorney,Lozano Smith’s Fresno office is seeking a tale...,195000.0,YEARLY,"Fresno County, CA",56120.0,1.0,NaN,120000.0,Full-time,NaN,1.713573e+12,NaN,https://www.linkedin.com/jobs/view/3906265349/...,NaN,ComplexOnsiteApply,1.716165e+12,NaN,Mid-Senior level,NaN,1.713573e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,93650.0,6019.0
28736,28736,3906267117,Lozano Smith,Title IX/Investigations Attorney,Our Walnut Creek office is currently seeking a...,195000.0,YEARLY,"Walnut Creek, CA",56120.0,1.0,NaN,120000.0,Full-time,NaN,1.713571e+12,NaN,https://www.linkedin.com/jobs/view/3906267117/...,NaN,ComplexOnsiteApply,1.716163e+12,NaN,Mid-Senior level,NaN,1.713571e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,94595.0,6013.0
28737,28737,3906267224,Solugenix,Marketing Social Media Specialist,Marketing Social Media Specialist - $70k – $75...,75000.0,YEARLY,"San Juan Capistrano, CA",43325.0,2.0,NaN,70000.0,Full-time,NaN,1.713573e+12,NaN,https://www.linkedin.com/jobs/view/3906267224/...,NaN,ComplexOnsiteApply,1.716165e+12,NaN,Mid-Senior level,NaN,1.713573e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,72500.0,92675.0,6059.0

In [27]:
posting_cleaned_filtered.set_index(['job_id', 'company_name'], inplace=True)
posting_cleaned_filtered

,,index,job_title,job_description,max_salary,pay_period,location,company_id,views,med_salary,min_salary,formatted_work_type,num_applicants,original_listed_time,remote_allowed,job_posting_url,application_url,application_type,expiry,closed_time,formatted_experience_level,skills_desc,listed_time,posting_domain,sponsored,work_type,currency,compensation_type,normalized_salary,zip_code,fips
job_id,company_name,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
921716,Corcoran Sawyer Smith,0,Marketing Coordinator,Job descriptionA leading real estate firm in N...,20.0,HOURLY,"Princeton, NJ",2774458.0,20.0,NaN,17.0,Full-time,2.0,1.713398e+12,NaN,https://www.linkedin.com/jobs/view/921716/?trk...,NaN,ComplexOnsiteApply,1.715990e+12,NaN,NaN,Requirements: \n\nWe are seeking a College or ...,1.713398e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,38480.0,8540.0,34021.0
10998357,The National Exemplar,1,Assitant Restaurant Manager,The National Exemplar is accepting application...,65000.0,YEARLY,"Cincinnati, OH",64896719.0,8.0,NaN,45000.0,Full-time,NaN,1.713278e+12,NaN,https://www.linkedin.com/jobs/view/10998357/?t...,NaN,ComplexOnsiteApply,1.715870e+12,NaN,NaN,We are currently accepting resumes for FOH - A...,1.713278e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,55000.0,45202.0,39061.0
23221523,"Abrams Fensterman, LLP",2,Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,175000.0,YEARLY,"New Hyde Park, NY",766262.0,16.0,NaN,140000.0,Full-time,NaN,1.712896e+12,NaN,https://www.linkedin.com/jobs/view/23221523/?t...,NaN,ComplexOnsiteApply,1.715488e+12,NaN,NaN,This position requires a baseline understandin...,1.712896e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,11040.0,36059.0
95428182,CLEVELAND KIDS BOOK BANK,3,Administrative Coordinator,Job Title: Administrative CoordinatorOrganizat...,NaN,HOURLY,"Cleveland, OH",55624331.0,1.0,25.0,NaN,Full-time,NaN,1.712856e+12,NaN,https://www.linkedin.com/jobs/view/95428182/?t...,https://www.kidsbookbank.org/employment/,OffsiteApply,1.715448e+12,NaN,NaN,NaN,1.712856e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,52000.0,44102.0,39035.0
266566927,Revesco Properties,4,Marketing & Office Coordinator,About Revesco Properties:Revesco Properties is...,75000.0,YEARLY,"Denver, CO",8577252.0,13.0,NaN,55000.0,Full-time,1.0,1.713459e+12,NaN,https://www.linkedin.com/jobs/view/266566927/?...,NaN,SimpleOnsiteApply,1.716051e+12,NaN,NaN,NaN,1.713459e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,65000.0,80202.0,8031.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3906265303,SPS,28733,Client Services Associate (42181),Job Title: Client Services Associate\n\n Repo...,18.0,HOURLY,"Nashville, TN",146075.0,3.0,NaN,18.0,Full-time,NaN,1.713572e+12,NaN,https://www.linkedin.com/jobs/view/3906265303/...,https://www.paycomonline.net/v4/ats/web.php/jo...,OffsiteApply,1.716165e+12,NaN,Entry level,NaN,1.713573e+12,www.paycomonline.net,0,FULL_TIME,USD,BASE_SALARY,37440.0,37201.0,47037.0
3906265332,Lozano Smith,28734,Litigation Legal Secretary,We currently have an opening in our Sacramento...,90000.0,YEARLY,"Sacramento, CA",56120.0,2.0,NaN,45000.0,Full-time,NaN,1.713572e+12,NaN,https://www.linkedin.com/jobs/view/3906265332/...,NaN,ComplexOnsiteApply,1.716164e+12,NaN,Associate,NaN,1.713572e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,67500.0,95811.0,6067.0
3906265349,Lozano Smith,28735,Labor & Employment Attorney,Lozano Smith’s Fresno office is seeking a tale...,195000.0,YEARLY,"Fresno County, CA",56120.0,1.0,NaN,120000.0,Full-time,NaN,1.713573e+12,NaN,https://www.linkedin.com/jobs/view/3906265349/...,NaN,ComplexOnsiteApply,1.716165e+12,NaN,Mid-Senior level,NaN,1.713573e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,93650.0,6019.0
3906267117,Lozano Smith,28736,Title IX/Investigations Attorney,Our Walnut Creek office is currently seeking a...,195000.0,YEARLY,"Walnut Creek, CA",56120.0,1.0,NaN,120000.0,Full-time,NaN,1.713571e+12,NaN,https://www.linkedin.com/jobs/view/3906267117/...,NaN,ComplexOnsiteApply,1.716163e+12,NaN,Mid-Senior level,NaN,1.713571e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,94595.0,6013.0
3906267224,Solugenix,28737,Marketing Social Media Specialist,Marketing Social Media Specialist - $70k – $75...,75000.0,YEARLY,"San Juan Capistrano, CA",43325.0,2.0,NaN,70000.0,Full-time,NaN,1.713573e+12,NaN,https://www.linkedin.com/jobs/view/3906267224/...,NaN,ComplexOnsiteApply,1.716165e+12,NaN,Mid-Senior level,NaN,1.713573e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,72500.0,92675.0,6059.0

In [28]:
posting_cleaned_filtered.sort_index()

,,index,job_title,job_description,max_salary,pay_period,location,company_id,views,med_salary,min_salary,formatted_work_type,num_applicants,original_listed_time,remote_allowed,job_posting_url,application_url,application_type,expiry,closed_time,formatted_experience_level,skills_desc,listed_time,posting_domain,sponsored,work_type,currency,compensation_type,normalized_salary,zip_code,fips
job_id,company_name,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
921716,Corcoran Sawyer Smith,0,Marketing Coordinator,Job descriptionA leading real estate firm in N...,20.0,HOURLY,"Princeton, NJ",2774458.0,20.0,NaN,17.0,Full-time,2.0,1.713398e+12,NaN,https://www.linkedin.com/jobs/view/921716/?trk...,NaN,ComplexOnsiteApply,1.715990e+12,NaN,NaN,Requirements: \n\nWe are seeking a College or ...,1.713398e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,38480.0,8540.0,34021.0
10998357,The National Exemplar,1,Assitant Restaurant Manager,The National Exemplar is accepting application...,65000.0,YEARLY,"Cincinnati, OH",64896719.0,8.0,NaN,45000.0,Full-time,NaN,1.713278e+12,NaN,https://www.linkedin.com/jobs/view/10998357/?t...,NaN,ComplexOnsiteApply,1.715870e+12,NaN,NaN,We are currently accepting resumes for FOH - A...,1.713278e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,55000.0,45202.0,39061.0
23221523,"Abrams Fensterman, LLP",2,Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,175000.0,YEARLY,"New Hyde Park, NY",766262.0,16.0,NaN,140000.0,Full-time,NaN,1.712896e+12,NaN,https://www.linkedin.com/jobs/view/23221523/?t...,NaN,ComplexOnsiteApply,1.715488e+12,NaN,NaN,This position requires a baseline understandin...,1.712896e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,11040.0,36059.0
95428182,CLEVELAND KIDS BOOK BANK,3,Administrative Coordinator,Job Title: Administrative CoordinatorOrganizat...,NaN,HOURLY,"Cleveland, OH",55624331.0,1.0,25.0,NaN,Full-time,NaN,1.712856e+12,NaN,https://www.linkedin.com/jobs/view/95428182/?t...,https://www.kidsbookbank.org/employment/,OffsiteApply,1.715448e+12,NaN,NaN,NaN,1.712856e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,52000.0,44102.0,39035.0
266566927,Revesco Properties,4,Marketing & Office Coordinator,About Revesco Properties:Revesco Properties is...,75000.0,YEARLY,"Denver, CO",8577252.0,13.0,NaN,55000.0,Full-time,1.0,1.713459e+12,NaN,https://www.linkedin.com/jobs/view/266566927/?...,NaN,SimpleOnsiteApply,1.716051e+12,NaN,NaN,NaN,1.713459e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,65000.0,80202.0,8031.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3906265303,SPS,28733,Client Services Associate (42181),Job Title: Client Services Associate\n\n Repo...,18.0,HOURLY,"Nashville, TN",146075.0,3.0,NaN,18.0,Full-time,NaN,1.713572e+12,NaN,https://www.linkedin.com/jobs/view/3906265303/...,https://www.paycomonline.net/v4/ats/web.php/jo...,OffsiteApply,1.716165e+12,NaN,Entry level,NaN,1.713573e+12,www.paycomonline.net,0,FULL_TIME,USD,BASE_SALARY,37440.0,37201.0,47037.0
3906265332,Lozano Smith,28734,Litigation Legal Secretary,We currently have an opening in our Sacramento...,90000.0,YEARLY,"Sacramento, CA",56120.0,2.0,NaN,45000.0,Full-time,NaN,1.713572e+12,NaN,https://www.linkedin.com/jobs/view/3906265332/...,NaN,ComplexOnsiteApply,1.716164e+12,NaN,Associate,NaN,1.713572e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,67500.0,95811.0,6067.0
3906265349,Lozano Smith,28735,Labor & Employment Attorney,Lozano Smith’s Fresno office is seeking a tale...,195000.0,YEARLY,"Fresno County, CA",56120.0,1.0,NaN,120000.0,Full-time,NaN,1.713573e+12,NaN,https://www.linkedin.com/jobs/view/3906265349/...,NaN,ComplexOnsiteApply,1.716165e+12,NaN,Mid-Senior level,NaN,1.713573e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,93650.0,6019.0
3906267117,Lozano Smith,28736,Title IX/Investigations Attorney,Our Walnut Creek office is currently seeking a...,195000.0,YEARLY,"Walnut Creek, CA",56120.0,1.0,NaN,120000.0,Full-time,NaN,1.713571e+12,NaN,https://www.linkedin.com/jobs/view/3906267117/...,NaN,ComplexOnsiteApply,1.716163e+12,NaN,Mid-Senior level,NaN,1.713571e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,94595.0,6013.0
3906267224,Solugenix,28737,Marketing Social Media Specialist,Marketing Social Media Specialist - $70k – $75...,75000.0,YEARLY,"San Juan Capistrano, CA",43325.0,2.0,NaN,70000.0,Full-time,NaN,1.713573e+12,NaN,https://www.linkedin.com/jobs/view/3906267224/...,NaN,ComplexOnsiteApply,1.716165e+12,NaN,Mid-Senior level,NaN,1.713573e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,72500.0,92675.0,6059.0

In [30]:
posting_cleaned_filtered.reset_index(inplace=True)
posting_cleaned_filtered

,level_0,job_id,company_name,index,job_title,job_description,max_salary,pay_period,location,company_id,views,med_salary,min_salary,formatted_work_type,num_applicants,original_listed_time,remote_allowed,job_posting_url,application_url,application_type,expiry,closed_time,formatted_experience_level,skills_desc,listed_time,posting_domain,sponsored,work_type,currency,compensation_type,normalized_salary,zip_code,fips
0,0,921716,Corcoran Sawyer Smith,0,Marketing Coordinator,Job descriptionA leading real estate firm in N...,20.0,HOURLY,"Princeton, NJ",2774458.0,20.0,NaN,17.0,Full-time,2.0,1.713398e+12,NaN,https://www.linkedin.com/jobs/view/921716/?trk...,NaN,ComplexOnsiteApply,1.715990e+12,NaN,NaN,Requirements: \n\nWe are seeking a College or ...,1.713398e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,38480.0,8540.0,34021.0
1,1,10998357,The National Exemplar,1,Assitant Restaurant Manager,The National Exemplar is accepting application...,65000.0,YEARLY,"Cincinnati, OH",64896719.0,8.0,NaN,45000.0,Full-time,NaN,1.713278e+12,NaN,https://www.linkedin.com/jobs/view/10998357/?t...,NaN,ComplexOnsiteApply,1.715870e+12,NaN,NaN,We are currently accepting resumes for FOH - A...,1.713278e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,55000.0,45202.0,39061.0
2,2,23221523,"Abrams Fensterman, LLP",2,Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,175000.0,YEARLY,"New Hyde Park, NY",766262.0,16.0,NaN,140000.0,Full-time,NaN,1.712896e+12,NaN,https://www.linkedin.com/jobs/view/23221523/?t...,NaN,ComplexOnsiteApply,1.715488e+12,NaN,NaN,This position requires a baseline understandin...,1.712896e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,11040.0,36059.0
3,3,95428182,CLEVELAND KIDS BOOK BANK,3,Administrative Coordinator,Job Title: Administrative CoordinatorOrganizat...,NaN,HOURLY,"Cleveland, OH",55624331.0,1.0,25.0,NaN,Full-time,NaN,1.712856e+12,NaN,https://www.linkedin.com/jobs/view/95428182/?t...,https://www.kidsbookbank.org/employment/,OffsiteApply,1.715448e+12,NaN,NaN,NaN,1.712856e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,52000.0,44102.0,39035.0
4,4,266566927,Revesco Properties,4,Marketing & Office Coordinator,About Revesco Properties:Revesco Properties is...,75000.0,YEARLY,"Denver, CO",8577252.0,13.0,NaN,55000.0,Full-time,1.0,1.713459e+12,NaN,https://www.linkedin.com/jobs/view/266566927/?...,NaN,SimpleOnsiteApply,1.716051e+12,NaN,NaN,NaN,1.713459e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,65000.0,80202.0,8031.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28733,28733,3906265303,SPS,28733,Client Services Associate (42181),Job Title: Client Services Associate\n\n Repo...,18.0,HOURLY,"Nashville, TN",146075.0,3.0,NaN,18.0,Full-time,NaN,1.713572e+12,NaN,https://www.linkedin.com/jobs/view/3906265303/...,https://www.paycomonline.net/v4/ats/web.php/jo...,OffsiteApply,1.716165e+12,NaN,Entry level,NaN,1.713573e+12,www.paycomonline.net,0,FULL_TIME,USD,BASE_SALARY,37440.0,37201.0,47037.0
28734,28734,3906265332,Lozano Smith,28734,Litigation Legal Secretary,We currently have an opening in our Sacramento...,90000.0,YEARLY,"Sacramento, CA",56120.0,2.0,NaN,45000.0,Full-time,NaN,1.713572e+12,NaN,https://www.linkedin.com/jobs/view/3906265332/...,NaN,ComplexOnsiteApply,1.716164e+12,NaN,Associate,NaN,1.713572e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,67500.0,95811.0,6067.0
28735,28735,3906265349,Lozano Smith,28735,Labor & Employment Attorney,Lozano Smith’s Fresno office is seeking a tale...,195000.0,YEARLY,"Fresno County, CA",56120.0,1.0,NaN,120000.0,Full-time,NaN,1.713573e+12,NaN,https://www.linkedin.com/jobs/view/3906265349/...,NaN,ComplexOnsiteApply,1.716165e+12,NaN,Mid-Senior level,NaN,1.713573e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,93650.0,6019.0
28736,28736,3906267117,Lozano Smith,28736,Title IX/Investigations Attorney,Our Walnut Creek office is currently seeking a...,195000.0,YEARLY,"Walnut Creek, CA",56120.0,1.0,NaN,120000.0,Full-time,NaN,1.713571e+12,NaN,https://www.linkedin.com/jobs/view/3906267117/...,NaN,ComplexOnsiteApply,1.716163e+12,NaN,Mid-Senior level,NaN,1.713571e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,94595.0,6013.0
28737,28737,3906267224,Solugenix,28737,Marketing Social Media Specialist,Marketing Social Media Specialist - $70k – $75...,75000.0,YEARLY,"San Juan Capistrano, CA",43325.0,2.0,NaN,70000.0,Full-time,NaN,1.713573e+12,NaN,https://www.linkedin.com/jobs/view/3906267224/...,NaN,ComplexOnsiteApply,1.716165e+12,NaN,Mid-Senior level,NaN,1.713573e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,72500.0,92675.0,6059.0

In [31]:
# posting_cleaned[posting_cleaned.duplicated(keep=False)]
posting_cleaned_filtered[posting_cleaned_filtered.duplicated(keep=False)]

Empty DataFrame
Columns: [level_0, job_id, company_name, index, job_title, job_description, max_salary, pay_period, location, company_id, views, med_salary, min_salary, formatted_work_type, num_applicants, original_listed_time, remote_allowed, job_posting_url, application_url, application_type, expiry, closed_time, formatted_experience_level, skills_desc, listed_time, posting_domain, sponsored, work_type, currency, compensation_type, normalized_salary, zip_code, fips]
Index: []

In [32]:
posting_cleaned_filtered

,level_0,job_id,company_name,index,job_title,job_description,max_salary,pay_period,location,company_id,views,med_salary,min_salary,formatted_work_type,num_applicants,original_listed_time,remote_allowed,job_posting_url,application_url,application_type,expiry,closed_time,formatted_experience_level,skills_desc,listed_time,posting_domain,sponsored,work_type,currency,compensation_type,normalized_salary,zip_code,fips
0,0,921716,Corcoran Sawyer Smith,0,Marketing Coordinator,Job descriptionA leading real estate firm in N...,20.0,HOURLY,"Princeton, NJ",2774458.0,20.0,NaN,17.0,Full-time,2.0,1.713398e+12,NaN,https://www.linkedin.com/jobs/view/921716/?trk...,NaN,ComplexOnsiteApply,1.715990e+12,NaN,NaN,Requirements: \n\nWe are seeking a College or ...,1.713398e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,38480.0,8540.0,34021.0
1,1,10998357,The National Exemplar,1,Assitant Restaurant Manager,The National Exemplar is accepting application...,65000.0,YEARLY,"Cincinnati, OH",64896719.0,8.0,NaN,45000.0,Full-time,NaN,1.713278e+12,NaN,https://www.linkedin.com/jobs/view/10998357/?t...,NaN,ComplexOnsiteApply,1.715870e+12,NaN,NaN,We are currently accepting resumes for FOH - A...,1.713278e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,55000.0,45202.0,39061.0
2,2,23221523,"Abrams Fensterman, LLP",2,Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,175000.0,YEARLY,"New Hyde Park, NY",766262.0,16.0,NaN,140000.0,Full-time,NaN,1.712896e+12,NaN,https://www.linkedin.com/jobs/view/23221523/?t...,NaN,ComplexOnsiteApply,1.715488e+12,NaN,NaN,This position requires a baseline understandin...,1.712896e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,11040.0,36059.0
3,3,95428182,CLEVELAND KIDS BOOK BANK,3,Administrative Coordinator,Job Title: Administrative CoordinatorOrganizat...,NaN,HOURLY,"Cleveland, OH",55624331.0,1.0,25.0,NaN,Full-time,NaN,1.712856e+12,NaN,https://www.linkedin.com/jobs/view/95428182/?t...,https://www.kidsbookbank.org/employment/,OffsiteApply,1.715448e+12,NaN,NaN,NaN,1.712856e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,52000.0,44102.0,39035.0
4,4,266566927,Revesco Properties,4,Marketing & Office Coordinator,About Revesco Properties:Revesco Properties is...,75000.0,YEARLY,"Denver, CO",8577252.0,13.0,NaN,55000.0,Full-time,1.0,1.713459e+12,NaN,https://www.linkedin.com/jobs/view/266566927/?...,NaN,SimpleOnsiteApply,1.716051e+12,NaN,NaN,NaN,1.713459e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,65000.0,80202.0,8031.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28733,28733,3906265303,SPS,28733,Client Services Associate (42181),Job Title: Client Services Associate\n\n Repo...,18.0,HOURLY,"Nashville, TN",146075.0,3.0,NaN,18.0,Full-time,NaN,1.713572e+12,NaN,https://www.linkedin.com/jobs/view/3906265303/...,https://www.paycomonline.net/v4/ats/web.php/jo...,OffsiteApply,1.716165e+12,NaN,Entry level,NaN,1.713573e+12,www.paycomonline.net,0,FULL_TIME,USD,BASE_SALARY,37440.0,37201.0,47037.0
28734,28734,3906265332,Lozano Smith,28734,Litigation Legal Secretary,We currently have an opening in our Sacramento...,90000.0,YEARLY,"Sacramento, CA",56120.0,2.0,NaN,45000.0,Full-time,NaN,1.713572e+12,NaN,https://www.linkedin.com/jobs/view/3906265332/...,NaN,ComplexOnsiteApply,1.716164e+12,NaN,Associate,NaN,1.713572e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,67500.0,95811.0,6067.0
28735,28735,3906265349,Lozano Smith,28735,Labor & Employment Attorney,Lozano Smith’s Fresno office is seeking a tale...,195000.0,YEARLY,"Fresno County, CA",56120.0,1.0,NaN,120000.0,Full-time,NaN,1.713573e+12,NaN,https://www.linkedin.com/jobs/view/3906265349/...,NaN,ComplexOnsiteApply,1.716165e+12,NaN,Mid-Senior level,NaN,1.713573e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,93650.0,6019.0
28736,28736,3906267117,Lozano Smith,28736,Title IX/Investigations Attorney,Our Walnut Creek office is currently seeking a...,195000.0,YEARLY,"Walnut Creek, CA",56120.0,1.0,NaN,120000.0,Full-time,NaN,1.713571e+12,NaN,https://www.linkedin.com/jobs/view/3906267117/...,NaN,ComplexOnsiteApply,1.716163e+12,NaN,Mid-Senior level,NaN,1.713571e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,94595.0,6013.0
28737,28737,3906267224,Solugenix,28737,Marketing Social Media Specialist,Marketing Social Media Specialist - $70k – $75...,75000.0,YEARLY,"San Juan Capistrano, CA",43325.0,2.0,NaN,70000.0,Full-time,NaN,1.713573e+12,NaN,https://www.linkedin.com/jobs/view/3906267224/...,NaN,ComplexOnsiteApply,1.716165e+12,NaN,Mid-Senior level,NaN,1.713573e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,72500.0,92675.0,6059.0

In [33]:
posting_cleaned_filtered.columns

Index(['level_0', 'job_id', 'company_name', 'index', 'job_title',
       'job_description', 'max_salary', 'pay_period', 'location', 'company_id',
       'views', 'med_salary', 'min_salary', 'formatted_work_type',
       'num_applicants', 'original_listed_time', 'remote_allowed',
       'job_posting_url', 'application_url', 'application_type', 'expiry',
       'closed_time', 'formatted_experience_level', 'skills_desc',
       'listed_time', 'posting_domain', 'sponsored', 'work_type', 'currency',
       'compensation_type', 'normalized_salary', 'zip_code', 'fips'],
      dtype='object')

In [34]:
posting_cleaned_filtered.drop(columns=['level_0'],inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_2628\1725546405.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  posting_cleaned_filtered.drop(columns=['level_0'],inplace=True)

In [35]:
posting_cleaned_filtered

,job_id,company_name,index,job_title,job_description,max_salary,pay_period,location,company_id,views,med_salary,min_salary,formatted_work_type,num_applicants,original_listed_time,remote_allowed,job_posting_url,application_url,application_type,expiry,closed_time,formatted_experience_level,skills_desc,listed_time,posting_domain,sponsored,work_type,currency,compensation_type,normalized_salary,zip_code,fips
0,921716,Corcoran Sawyer Smith,0,Marketing Coordinator,Job descriptionA leading real estate firm in N...,20.0,HOURLY,"Princeton, NJ",2774458.0,20.0,NaN,17.0,Full-time,2.0,1.713398e+12,NaN,https://www.linkedin.com/jobs/view/921716/?trk...,NaN,ComplexOnsiteApply,1.715990e+12,NaN,NaN,Requirements: \n\nWe are seeking a College or ...,1.713398e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,38480.0,8540.0,34021.0
1,10998357,The National Exemplar,1,Assitant Restaurant Manager,The National Exemplar is accepting application...,65000.0,YEARLY,"Cincinnati, OH",64896719.0,8.0,NaN,45000.0,Full-time,NaN,1.713278e+12,NaN,https://www.linkedin.com/jobs/view/10998357/?t...,NaN,ComplexOnsiteApply,1.715870e+12,NaN,NaN,We are currently accepting resumes for FOH - A...,1.713278e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,55000.0,45202.0,39061.0
2,23221523,"Abrams Fensterman, LLP",2,Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,175000.0,YEARLY,"New Hyde Park, NY",766262.0,16.0,NaN,140000.0,Full-time,NaN,1.712896e+12,NaN,https://www.linkedin.com/jobs/view/23221523/?t...,NaN,ComplexOnsiteApply,1.715488e+12,NaN,NaN,This position requires a baseline understandin...,1.712896e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,11040.0,36059.0
3,95428182,CLEVELAND KIDS BOOK BANK,3,Administrative Coordinator,Job Title: Administrative CoordinatorOrganizat...,NaN,HOURLY,"Cleveland, OH",55624331.0,1.0,25.0,NaN,Full-time,NaN,1.712856e+12,NaN,https://www.linkedin.com/jobs/view/95428182/?t...,https://www.kidsbookbank.org/employment/,OffsiteApply,1.715448e+12,NaN,NaN,NaN,1.712856e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,52000.0,44102.0,39035.0
4,266566927,Revesco Properties,4,Marketing & Office Coordinator,About Revesco Properties:Revesco Properties is...,75000.0,YEARLY,"Denver, CO",8577252.0,13.0,NaN,55000.0,Full-time,1.0,1.713459e+12,NaN,https://www.linkedin.com/jobs/view/266566927/?...,NaN,SimpleOnsiteApply,1.716051e+12,NaN,NaN,NaN,1.713459e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,65000.0,80202.0,8031.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28733,3906265303,SPS,28733,Client Services Associate (42181),Job Title: Client Services Associate\n\n Repo...,18.0,HOURLY,"Nashville, TN",146075.0,3.0,NaN,18.0,Full-time,NaN,1.713572e+12,NaN,https://www.linkedin.com/jobs/view/3906265303/...,https://www.paycomonline.net/v4/ats/web.php/jo...,OffsiteApply,1.716165e+12,NaN,Entry level,NaN,1.713573e+12,www.paycomonline.net,0,FULL_TIME,USD,BASE_SALARY,37440.0,37201.0,47037.0
28734,3906265332,Lozano Smith,28734,Litigation Legal Secretary,We currently have an opening in our Sacramento...,90000.0,YEARLY,"Sacramento, CA",56120.0,2.0,NaN,45000.0,Full-time,NaN,1.713572e+12,NaN,https://www.linkedin.com/jobs/view/3906265332/...,NaN,ComplexOnsiteApply,1.716164e+12,NaN,Associate,NaN,1.713572e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,67500.0,95811.0,6067.0
28735,3906265349,Lozano Smith,28735,Labor & Employment Attorney,Lozano Smith’s Fresno office is seeking a tale...,195000.0,YEARLY,"Fresno County, CA",56120.0,1.0,NaN,120000.0,Full-time,NaN,1.713573e+12,NaN,https://www.linkedin.com/jobs/view/3906265349/...,NaN,ComplexOnsiteApply,1.716165e+12,NaN,Mid-Senior level,NaN,1.713573e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,93650.0,6019.0
28736,3906267117,Lozano Smith,28736,Title IX/Investigations Attorney,Our Walnut Creek office is currently seeking a...,195000.0,YEARLY,"Walnut Creek, CA",56120.0,1.0,NaN,120000.0,Full-time,NaN,1.713571e+12,NaN,https://www.linkedin.com/jobs/view/3906267117/...,NaN,ComplexOnsiteApply,1.716163e+12,NaN,Mid-Senior level,NaN,1.713571e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,94595.0,6013.0
28737,3906267224,Solugenix,28737,Marketing Social Media Specialist,Marketing Social Media Specialist - $70k – $75...,75000.0,YEARLY,"San Juan Capistrano, CA",43325.0,2.0,NaN,70000.0,Full-time,NaN,1.713573e+12,NaN,https://www.linkedin.com/jobs/view/3906267224/...,NaN,ComplexOnsiteApply,1.716165e+12,NaN,Mid-Senior level,NaN,1.713573e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,72500.0,92675.0,6059.0

In [ ]:
posting_cleaned_filtered.columns[posting_cleaned_filtered.columns.duplicated()]

Index([], dtype='object')